# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taynara Limä
email: brito.taynara@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Taynara Limä Graphic Design Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taynaralim.github.io" # the base hostname & protocol for your site

# Contact settings
behance_username: TYRLFOLIO
phone_region: "+55 011"
phone_number: "962. 914. 536"

# About settings
location: "SP BR"

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: _sass
